### ISSUE TITLE
All languages in custom distribution

### ISSUE THREAD

**Issue by tearwyx** [researchgate/react-fast-highlight#145]
Hi, thanks for the module, but i have to disagree with the following text in `README.md`:

> #### Custom `highlight.js` distribution
> In cases where you bundle this component with a module bundler such as webpack, rollup or browserify and you know upfront which languages you want to support you can supply a custom distribution of `highlight.js`. This ensures you are not bundling all available languages of `highlight.js` which reduces the size of your bundle.
> 
> A custom distribution might look like this
> ```js
> import hljs from 'highlight.js/lib/highlight';
>  
> // Lets only register javascript, scss, html/xml
> hljs.registerLanguage('scss', require('highlight.js/lib/languages/scss'));
> hljs.registerLanguage('javascript', require('highlight.js/lib/languages/javascript'));
> hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'));
>  
> export default hljs;
> ```
> To actually use a custom distribution you need to use the `BareHighlight` component. With it you can build your wrapper for highlighting code.
> ```jsx
> import React, { Component } from 'react';
> import { BareHighlight } from 'react-fast-highlight';
> import hljs from './customhljs';
>  
> class CustomHighlight extends Component {
>   render() {
>     const { children, ...props } = this.props;
>     return (
>       <BareHighlight {...props} highlightjs={hljs}>
>         {children}
>       </BareHighlight>
>     );
> }
> ```
> Now you can use this wrapper the same way as the default `Highlight` component with only support for certain languages included.

This  "custom distribution" is useless and bundle is not reduced because we did not get rid of the unwanted languages.

Import/require stack:

* Importing `react-fast-highlight` (it is `react-fast-highlight/lib/index.js`).
  * Requiring `react-fast-highlight/lib/Highlight.js`.
    * Requiring `highlight.js` (it is `highlight.js/lib/index.js`).
        * Requiring all languages.

**Comment by danez** [comment]
thats why you need to only import `BareHighlight`
Either with
```js
import { BareHighlight } from 'react-fast-highlight';
```

like in the example or with require

```js
const BareHighlight = require('react-fast-highlight/lib/BareHighlight')
```

If you follow the example it should work perfectly

**Comment by danez** [comment]
Okay I think I see what you mean, i will check.

**Comment by danez** [comment]
You are right the example is wrong.

We import it like this:

```js
import BareHighlight from 'react-fast-highlight/lib/BareHighlight';
```

It seems I forgot to update the README

**Comment by danez** [comment]
Okay I fixed the readme.
